### ISSUE TITLE
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear(); breaking the sign in

### ISSUE THREAD

**Issue by kuncevic** [mclark1129/IdentityServer4.Samples#2]
I just replaced this `UseCookieAuthentication` with `UseJwtBearerAuthentication`:

```
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            app.UseJwtBearerAuthentication(new JwtBearerOptions()
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                Authority = ientityServerUrl,
                Audience = ientityServerUrl,

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                RequireHttpsMetadata = false,

                TokenValidationParameters = new TokenValidationParameters()
                {
                    ClockSkew = TimeSpan.Zero,
                    NameClaimType = ClaimTypes.Name,
                    RoleClaimType = ClaimTypes.Role
                },
            });
```
This way it just redirected me back from Azure to Login page. But discovered if I comment `JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();` it is working. 

However exactly same configuration is working well in case of google login. 

Any thoughts why `DefaultInboundClaimTypeMap.Clear();` is breaking Azure login?

What is `JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();` is actually doing described here:
https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by mclark1129** [comment]
@kuncevic If I had to guess, I think its because you are setting `NameClaimType` to `ClaimTypes.Name`.  The `ClaimTypes` constants map to the standard MS claim type values, not JWT claim types.

By default, the `OpenIdConnectMiddleware` will map standard JWT claim names to the classic M$ claim names.   Calling `JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();` will erase that mapping.

Try using:

                TokenValidationParameters = new TokenValidationParameters()
                {
                    ClockSkew = TimeSpan.Zero,
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role
                },
