### ISSUE TITLE
Indefinite loop after login in IdentityServer AAD Sample

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [mclark1129/IdentityServer4.Samples#3]
I've run the sample and experienced indefinite loop after login when using Chrome

http://localhost:5000/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636272121274625996.NmNiMmFmNjQtYjViOC00MzU5LTlmZmUtYmQyNmJmMTNlODMzYmUxYTkzNGYtYjNmZS00M2UzLTlkYjctYzg4ZmNiY2ZkNDQ0&state=CfDJ8D1klo7iHCpKkjerDgZTfv8CT-qVdA0KOFZ-xrhZwTgkZp9U4yeNQmesIK8xN5HZxuAqxFDDWWWGYPGcbkUvztlZLSwwcBrernS0gu-usyLwX0dib699eBBwToPN8yrg_LMyQfYpP2fI606ULy1Bw4OcXwjmUZJEiLAxLQLDiHYW2u_f3j-4vtN1FY_Z4w2mLgHkZzICPZ5S-bwpjjHUrLkRSzgbwNlTW3ldjY2RCN_GEO4zLpOPm90W0HMrZt7gCl5EI6lIsNW6W7Sf3J06eBiSlHeSp3-Jt15IgoLKxS8lqik_C1p5zl_fA0OvqtB_uaBZan4C40U4_r-_PS4LrKcIuMixfqRDWFVPZiExC0VdH-2Ig_4y8MUrSDo1HM6Uhg

According to Fiddler, POST http://localhost:5002/signin-oidc redirects to http://localhost:5002/Home/Secure, 
but GET http://localhost:5002/Home/Secure  redirects back to
http://localhost:5000/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636272129147865486.MjZhM2MyMjctMzMyNy00YTA0LThmNmUtODNmN2YxNGM4ZjFlNjQwZDU4YTEtMDk4My00NzZkLTgyZGItMzdkOThkYWQzMGEy&state=CfDJ8D1klo7iHCpKkjerDgZTfv9n27wPkGBFzN6T6e9aOGmDW95rnL7_ojCOHDgDUJrdd26Fp3FYqf2xnRm1woexd4CgM6ZqgG3CybWq_5i7MsRMy2W5SXRYCqYA1jzdVYXy5R5YSuAt_37mcOwsmhk64v5dZlHcvWSOvpe2tEcr9h5a3DR4WSnRrHP80RkRQibhbOrMmqtwhMF6rym0g1xcRAP1SqT8q8xBtom2tS98_eiDDeUXhHT-mAzffHTROT4cP3gNLu958RdrNqCnRnq5gcQOvCUOU9X2ss20ClCff9hDH6xgjEPOR3A-Zj__WjSQsfQXvXJQkPb8oSLciYI-k8Cp--YlSmoER06OdBlJ_SiRzA5FGSjhulUF3dtcR0ozIw

When I opened http://localhost:5002/ in Firefox, after login it successfully ended up on http://localhost:5002/Home/Secure

Debug output includes hundreds of repeated messages:
```
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware:Information: AuthenticationScheme: Cookies signed in.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 245.2494ms 302
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5002/Home/Secure 
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed for user: .
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Warning: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware:Information: AuthenticationScheme: oidc was challenged.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 15.2312ms 302
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:5002/signin-oidc application/x-www-form-urlencoded 1818
```

Fiddler logs are attached [IdSrv4_AADSample_InvdefiniteLoop.zip](https://github.com/mclark1129/IdentityServer4.Samples/files/907157/IdSrv4_AADSample_InvdefiniteLoop.zip)

I am not sure is the issue specific to AAD or in general to IdentityServer4, but I prefer to resolve, find workaround or at least understand the cause before implementing IdentityServer4  in production code.

**Comment by michael-freidgeim-webjet** [comment]
The indefinite loop seems related, that I've already was logged-on to the browser. When I tried to use Incognito window, redirection worked correctly.

**Comment by mclark1129** [comment]
@michael-freidgeim-webjet It's possible that at some point when debugging the process either crashed or was stopped prematurely, leaving you with a cookie that was in an invalid state.  I'd recommend clearing your cookies and cache and trying again.
